/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class _xtract_function_descriptor_algo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _xtract_function_descriptor_algo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_xtract_function_descriptor_algo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xtractJNI.delete__xtract_function_descriptor_algo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    xtractJNI._xtract_function_descriptor_algo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return xtractJNI._xtract_function_descriptor_algo_name_get(swigCPtr, this);
  }

  public void setP_name(String value) {
    xtractJNI._xtract_function_descriptor_algo_p_name_set(swigCPtr, this, value);
  }

  public String getP_name() {
    return xtractJNI._xtract_function_descriptor_algo_p_name_get(swigCPtr, this);
  }

  public void setDesc(String value) {
    xtractJNI._xtract_function_descriptor_algo_desc_set(swigCPtr, this, value);
  }

  public String getDesc() {
    return xtractJNI._xtract_function_descriptor_algo_desc_get(swigCPtr, this);
  }

  public void setP_desc(String value) {
    xtractJNI._xtract_function_descriptor_algo_p_desc_set(swigCPtr, this, value);
  }

  public String getP_desc() {
    return xtractJNI._xtract_function_descriptor_algo_p_desc_get(swigCPtr, this);
  }

  public void setAuthor(String value) {
    xtractJNI._xtract_function_descriptor_algo_author_set(swigCPtr, this, value);
  }

  public String getAuthor() {
    return xtractJNI._xtract_function_descriptor_algo_author_get(swigCPtr, this);
  }

  public void setYear(int value) {
    xtractJNI._xtract_function_descriptor_algo_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return xtractJNI._xtract_function_descriptor_algo_year_get(swigCPtr, this);
  }

  public _xtract_function_descriptor_algo() {
    this(xtractJNI.new__xtract_function_descriptor_algo(), true);
  }

}
