/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class _xtract_function_descriptor_argv {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _xtract_function_descriptor_argv(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_xtract_function_descriptor_argv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xtractJNI.delete__xtract_function_descriptor_argv(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(xtract_type_t value) {
    xtractJNI._xtract_function_descriptor_argv_type_set(swigCPtr, this, value.swigValue());
  }

  public xtract_type_t getType() {
    return xtract_type_t.swigToEnum(xtractJNI._xtract_function_descriptor_argv_type_get(swigCPtr, this));
  }

  public void setMin(SWIGTYPE_p_double value) {
    xtractJNI._xtract_function_descriptor_argv_min_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getMin() {
    long cPtr = xtractJNI._xtract_function_descriptor_argv_min_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setMax(SWIGTYPE_p_double value) {
    xtractJNI._xtract_function_descriptor_argv_max_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getMax() {
    long cPtr = xtractJNI._xtract_function_descriptor_argv_max_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setDef(SWIGTYPE_p_double value) {
    xtractJNI._xtract_function_descriptor_argv_def_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getDef() {
    long cPtr = xtractJNI._xtract_function_descriptor_argv_def_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setUnit(SWIGTYPE_p_unit_ value) {
    xtractJNI._xtract_function_descriptor_argv_unit_set(swigCPtr, this, SWIGTYPE_p_unit_.getCPtr(value));
  }

  public SWIGTYPE_p_unit_ getUnit() {
    long cPtr = xtractJNI._xtract_function_descriptor_argv_unit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unit_(cPtr, false);
  }

  public void setDonor(SWIGTYPE_p_int value) {
    xtractJNI._xtract_function_descriptor_argv_donor_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getDonor() {
    long cPtr = xtractJNI._xtract_function_descriptor_argv_donor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public _xtract_function_descriptor_argv() {
    this(xtractJNI.new__xtract_function_descriptor_argv(), true);
  }

}
