/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class _xtract_function_descriptor_data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _xtract_function_descriptor_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_xtract_function_descriptor_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xtractJNI.delete__xtract_function_descriptor_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormat(xtract_vector_t value) {
    xtractJNI._xtract_function_descriptor_data_format_set(swigCPtr, this, value.swigValue());
  }

  public xtract_vector_t getFormat() {
    return xtract_vector_t.swigToEnum(xtractJNI._xtract_function_descriptor_data_format_get(swigCPtr, this));
  }

  public void setUnit(xtract_unit_t value) {
    xtractJNI._xtract_function_descriptor_data_unit_set(swigCPtr, this, value.swigValue());
  }

  public xtract_unit_t getUnit() {
    return xtract_unit_t.swigToEnum(xtractJNI._xtract_function_descriptor_data_unit_get(swigCPtr, this));
  }

  public _xtract_function_descriptor_data() {
    this(xtractJNI.new__xtract_function_descriptor_data(), true);
  }

}
