/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_spectrum_ {
  public final static xtract_spectrum_ XTRACT_MAGNITUDE_SPECTRUM = new xtract_spectrum_("XTRACT_MAGNITUDE_SPECTRUM");
  public final static xtract_spectrum_ XTRACT_LOG_MAGNITUDE_SPECTRUM = new xtract_spectrum_("XTRACT_LOG_MAGNITUDE_SPECTRUM");
  public final static xtract_spectrum_ XTRACT_POWER_SPECTRUM = new xtract_spectrum_("XTRACT_POWER_SPECTRUM");
  public final static xtract_spectrum_ XTRACT_LOG_POWER_SPECTRUM = new xtract_spectrum_("XTRACT_LOG_POWER_SPECTRUM");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_spectrum_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_spectrum_.class + " with value " + swigValue);
  }

  private xtract_spectrum_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_spectrum_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_spectrum_(String swigName, xtract_spectrum_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_spectrum_[] swigValues = { XTRACT_MAGNITUDE_SPECTRUM, XTRACT_LOG_MAGNITUDE_SPECTRUM, XTRACT_POWER_SPECTRUM, XTRACT_LOG_POWER_SPECTRUM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

