/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_features_ {
  public final static xtract_features_ XTRACT_MEAN = new xtract_features_("XTRACT_MEAN");
  public final static xtract_features_ XTRACT_VARIANCE = new xtract_features_("XTRACT_VARIANCE");
  public final static xtract_features_ XTRACT_STANDARD_DEVIATION = new xtract_features_("XTRACT_STANDARD_DEVIATION");
  public final static xtract_features_ XTRACT_AVERAGE_DEVIATION = new xtract_features_("XTRACT_AVERAGE_DEVIATION");
  public final static xtract_features_ XTRACT_SKEWNESS = new xtract_features_("XTRACT_SKEWNESS");
  public final static xtract_features_ XTRACT_KURTOSIS = new xtract_features_("XTRACT_KURTOSIS");
  public final static xtract_features_ XTRACT_SPECTRAL_MEAN = new xtract_features_("XTRACT_SPECTRAL_MEAN");
  public final static xtract_features_ XTRACT_SPECTRAL_VARIANCE = new xtract_features_("XTRACT_SPECTRAL_VARIANCE");
  public final static xtract_features_ XTRACT_SPECTRAL_STANDARD_DEVIATION = new xtract_features_("XTRACT_SPECTRAL_STANDARD_DEVIATION");
  public final static xtract_features_ XTRACT_SPECTRAL_SKEWNESS = new xtract_features_("XTRACT_SPECTRAL_SKEWNESS");
  public final static xtract_features_ XTRACT_SPECTRAL_KURTOSIS = new xtract_features_("XTRACT_SPECTRAL_KURTOSIS");
  public final static xtract_features_ XTRACT_SPECTRAL_CENTROID = new xtract_features_("XTRACT_SPECTRAL_CENTROID");
  public final static xtract_features_ XTRACT_IRREGULARITY_K = new xtract_features_("XTRACT_IRREGULARITY_K");
  public final static xtract_features_ XTRACT_IRREGULARITY_J = new xtract_features_("XTRACT_IRREGULARITY_J");
  public final static xtract_features_ XTRACT_TRISTIMULUS_1 = new xtract_features_("XTRACT_TRISTIMULUS_1");
  public final static xtract_features_ XTRACT_TRISTIMULUS_2 = new xtract_features_("XTRACT_TRISTIMULUS_2");
  public final static xtract_features_ XTRACT_TRISTIMULUS_3 = new xtract_features_("XTRACT_TRISTIMULUS_3");
  public final static xtract_features_ XTRACT_SMOOTHNESS = new xtract_features_("XTRACT_SMOOTHNESS");
  public final static xtract_features_ XTRACT_SPREAD = new xtract_features_("XTRACT_SPREAD");
  public final static xtract_features_ XTRACT_ZCR = new xtract_features_("XTRACT_ZCR");
  public final static xtract_features_ XTRACT_ROLLOFF = new xtract_features_("XTRACT_ROLLOFF");
  public final static xtract_features_ XTRACT_LOUDNESS = new xtract_features_("XTRACT_LOUDNESS");
  public final static xtract_features_ XTRACT_FLATNESS = new xtract_features_("XTRACT_FLATNESS");
  public final static xtract_features_ XTRACT_FLATNESS_DB = new xtract_features_("XTRACT_FLATNESS_DB");
  public final static xtract_features_ XTRACT_TONALITY = new xtract_features_("XTRACT_TONALITY");
  public final static xtract_features_ XTRACT_CREST = new xtract_features_("XTRACT_CREST");
  public final static xtract_features_ XTRACT_NOISINESS = new xtract_features_("XTRACT_NOISINESS");
  public final static xtract_features_ XTRACT_RMS_AMPLITUDE = new xtract_features_("XTRACT_RMS_AMPLITUDE");
  public final static xtract_features_ XTRACT_SPECTRAL_INHARMONICITY = new xtract_features_("XTRACT_SPECTRAL_INHARMONICITY");
  public final static xtract_features_ XTRACT_POWER = new xtract_features_("XTRACT_POWER");
  public final static xtract_features_ XTRACT_ODD_EVEN_RATIO = new xtract_features_("XTRACT_ODD_EVEN_RATIO");
  public final static xtract_features_ XTRACT_SHARPNESS = new xtract_features_("XTRACT_SHARPNESS");
  public final static xtract_features_ XTRACT_SPECTRAL_SLOPE = new xtract_features_("XTRACT_SPECTRAL_SLOPE");
  public final static xtract_features_ XTRACT_LOWEST_VALUE = new xtract_features_("XTRACT_LOWEST_VALUE");
  public final static xtract_features_ XTRACT_HIGHEST_VALUE = new xtract_features_("XTRACT_HIGHEST_VALUE");
  public final static xtract_features_ XTRACT_SUM = new xtract_features_("XTRACT_SUM");
  public final static xtract_features_ XTRACT_NONZERO_COUNT = new xtract_features_("XTRACT_NONZERO_COUNT");
  public final static xtract_features_ XTRACT_HPS = new xtract_features_("XTRACT_HPS");
  public final static xtract_features_ XTRACT_F0 = new xtract_features_("XTRACT_F0");
  public final static xtract_features_ XTRACT_FAILSAFE_F0 = new xtract_features_("XTRACT_FAILSAFE_F0");
  public final static xtract_features_ XTRACT_WAVELET_F0 = new xtract_features_("XTRACT_WAVELET_F0");
  public final static xtract_features_ XTRACT_MIDICENT = new xtract_features_("XTRACT_MIDICENT");
  public final static xtract_features_ XTRACT_LNORM = new xtract_features_("XTRACT_LNORM");
  public final static xtract_features_ XTRACT_FLUX = new xtract_features_("XTRACT_FLUX");
  public final static xtract_features_ XTRACT_ATTACK_TIME = new xtract_features_("XTRACT_ATTACK_TIME");
  public final static xtract_features_ XTRACT_DECAY_TIME = new xtract_features_("XTRACT_DECAY_TIME");
  public final static xtract_features_ XTRACT_DIFFERENCE_VECTOR = new xtract_features_("XTRACT_DIFFERENCE_VECTOR");
  public final static xtract_features_ XTRACT_AUTOCORRELATION = new xtract_features_("XTRACT_AUTOCORRELATION");
  public final static xtract_features_ XTRACT_AMDF = new xtract_features_("XTRACT_AMDF");
  public final static xtract_features_ XTRACT_ASDF = new xtract_features_("XTRACT_ASDF");
  public final static xtract_features_ XTRACT_BARK_COEFFICIENTS = new xtract_features_("XTRACT_BARK_COEFFICIENTS");
  public final static xtract_features_ XTRACT_PEAK_SPECTRUM = new xtract_features_("XTRACT_PEAK_SPECTRUM");
  public final static xtract_features_ XTRACT_SPECTRUM = new xtract_features_("XTRACT_SPECTRUM");
  public final static xtract_features_ XTRACT_AUTOCORRELATION_FFT = new xtract_features_("XTRACT_AUTOCORRELATION_FFT");
  public final static xtract_features_ XTRACT_MFCC = new xtract_features_("XTRACT_MFCC");
  public final static xtract_features_ XTRACT_DCT = new xtract_features_("XTRACT_DCT");
  public final static xtract_features_ XTRACT_HARMONIC_SPECTRUM = new xtract_features_("XTRACT_HARMONIC_SPECTRUM");
  public final static xtract_features_ XTRACT_LPC = new xtract_features_("XTRACT_LPC");
  public final static xtract_features_ XTRACT_LPCC = new xtract_features_("XTRACT_LPCC");
  public final static xtract_features_ XTRACT_SUBBANDS = new xtract_features_("XTRACT_SUBBANDS");
  public final static xtract_features_ XTRACT_WINDOWED = new xtract_features_("XTRACT_WINDOWED");
  public final static xtract_features_ XTRACT_SMOOTHED = new xtract_features_("XTRACT_SMOOTHED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_features_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_features_.class + " with value " + swigValue);
  }

  private xtract_features_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_features_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_features_(String swigName, xtract_features_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_features_[] swigValues = { XTRACT_MEAN, XTRACT_VARIANCE, XTRACT_STANDARD_DEVIATION, XTRACT_AVERAGE_DEVIATION, XTRACT_SKEWNESS, XTRACT_KURTOSIS, XTRACT_SPECTRAL_MEAN, XTRACT_SPECTRAL_VARIANCE, XTRACT_SPECTRAL_STANDARD_DEVIATION, XTRACT_SPECTRAL_SKEWNESS, XTRACT_SPECTRAL_KURTOSIS, XTRACT_SPECTRAL_CENTROID, XTRACT_IRREGULARITY_K, XTRACT_IRREGULARITY_J, XTRACT_TRISTIMULUS_1, XTRACT_TRISTIMULUS_2, XTRACT_TRISTIMULUS_3, XTRACT_SMOOTHNESS, XTRACT_SPREAD, XTRACT_ZCR, XTRACT_ROLLOFF, XTRACT_LOUDNESS, XTRACT_FLATNESS, XTRACT_FLATNESS_DB, XTRACT_TONALITY, XTRACT_CREST, XTRACT_NOISINESS, XTRACT_RMS_AMPLITUDE, XTRACT_SPECTRAL_INHARMONICITY, XTRACT_POWER, XTRACT_ODD_EVEN_RATIO, XTRACT_SHARPNESS, XTRACT_SPECTRAL_SLOPE, XTRACT_LOWEST_VALUE, XTRACT_HIGHEST_VALUE, XTRACT_SUM, XTRACT_NONZERO_COUNT, XTRACT_HPS, XTRACT_F0, XTRACT_FAILSAFE_F0, XTRACT_WAVELET_F0, XTRACT_MIDICENT, XTRACT_LNORM, XTRACT_FLUX, XTRACT_ATTACK_TIME, XTRACT_DECAY_TIME, XTRACT_DIFFERENCE_VECTOR, XTRACT_AUTOCORRELATION, XTRACT_AMDF, XTRACT_ASDF, XTRACT_BARK_COEFFICIENTS, XTRACT_PEAK_SPECTRUM, XTRACT_SPECTRUM, XTRACT_AUTOCORRELATION_FFT, XTRACT_MFCC, XTRACT_DCT, XTRACT_HARMONIC_SPECTRUM, XTRACT_LPC, XTRACT_LPCC, XTRACT_SUBBANDS, XTRACT_WINDOWED, XTRACT_SMOOTHED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

