/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xtract_function_descriptor_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected xtract_function_descriptor_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xtract_function_descriptor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xtractJNI.delete_xtract_function_descriptor_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    xtractJNI.xtract_function_descriptor_t_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return xtractJNI.xtract_function_descriptor_t_id_get(swigCPtr, this);
  }

  public _xtract_function_descriptor_algo getAlgo() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_algo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _xtract_function_descriptor_algo(cPtr, false);
  }

  public _xtract_function_descriptor_data getData() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _xtract_function_descriptor_data(cPtr, false);
  }

  public void setArgc(int value) {
    xtractJNI.xtract_function_descriptor_t_argc_set(swigCPtr, this, value);
  }

  public int getArgc() {
    return xtractJNI.xtract_function_descriptor_t_argc_get(swigCPtr, this);
  }

  public _xtract_function_descriptor_argv getArgv() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_argv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _xtract_function_descriptor_argv(cPtr, false);
  }

  public void setIs_scalar(xtract_bool_t value) {
    xtractJNI.xtract_function_descriptor_t_is_scalar_set(swigCPtr, this, value.swigValue());
  }

  public xtract_bool_t getIs_scalar() {
    return xtract_bool_t.swigToEnum(xtractJNI.xtract_function_descriptor_t_is_scalar_get(swigCPtr, this));
  }

  public void setIs_delta(xtract_bool_t value) {
    xtractJNI.xtract_function_descriptor_t_is_delta_set(swigCPtr, this, value.swigValue());
  }

  public xtract_bool_t getIs_delta() {
    return xtract_bool_t.swigToEnum(xtractJNI.xtract_function_descriptor_t_is_delta_get(swigCPtr, this));
  }

  public _xtract_function_descriptor_result getResult() {
    long cPtr = xtractJNI.xtract_function_descriptor_t_result_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _xtract_function_descriptor_result(cPtr, false);
  }

  public xtract_function_descriptor_t() {
    this(xtractJNI.new_xtract_function_descriptor_t(), true);
  }

}
