/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_bool_t {
  public final static xtract_bool_t XTRACT_FALSE = new xtract_bool_t("XTRACT_FALSE");
  public final static xtract_bool_t XTRACT_TRUE = new xtract_bool_t("XTRACT_TRUE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_bool_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_bool_t.class + " with value " + swigValue);
  }

  private xtract_bool_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_bool_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_bool_t(String swigName, xtract_bool_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_bool_t[] swigValues = { XTRACT_FALSE, XTRACT_TRUE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

