/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class xtract_mel_filter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected xtract_mel_filter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(xtract_mel_filter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        xtractJNI.delete_xtract_mel_filter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN_filters(int value) {
    xtractJNI.xtract_mel_filter_n_filters_set(swigCPtr, this, value);
  }

  public int getN_filters() {
    return xtractJNI.xtract_mel_filter_n_filters_get(swigCPtr, this);
  }

  public void setFilters(SWIGTYPE_p_p_double value) {
    xtractJNI.xtract_mel_filter_filters_set(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_p_double getFilters() {
    long cPtr = xtractJNI.xtract_mel_filter_filters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public xtract_mel_filter() {
    this(xtractJNI.new_xtract_mel_filter(), true);
  }

}
