/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_lnorm_filter_types_ {
  public final static xtract_lnorm_filter_types_ XTRACT_NO_LNORM_FILTER = new xtract_lnorm_filter_types_("XTRACT_NO_LNORM_FILTER");
  public final static xtract_lnorm_filter_types_ XTRACT_POSITIVE_SLOPE = new xtract_lnorm_filter_types_("XTRACT_POSITIVE_SLOPE");
  public final static xtract_lnorm_filter_types_ XTRACT_NEGATIVE_SLOPE = new xtract_lnorm_filter_types_("XTRACT_NEGATIVE_SLOPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_lnorm_filter_types_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_lnorm_filter_types_.class + " with value " + swigValue);
  }

  private xtract_lnorm_filter_types_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_lnorm_filter_types_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_lnorm_filter_types_(String swigName, xtract_lnorm_filter_types_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_lnorm_filter_types_[] swigValues = { XTRACT_NO_LNORM_FILTER, XTRACT_POSITIVE_SLOPE, XTRACT_NEGATIVE_SLOPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

