/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_window_types_ {
  public final static xtract_window_types_ XTRACT_GAUSS = new xtract_window_types_("XTRACT_GAUSS");
  public final static xtract_window_types_ XTRACT_HAMMING = new xtract_window_types_("XTRACT_HAMMING");
  public final static xtract_window_types_ XTRACT_HANN = new xtract_window_types_("XTRACT_HANN");
  public final static xtract_window_types_ XTRACT_BARTLETT = new xtract_window_types_("XTRACT_BARTLETT");
  public final static xtract_window_types_ XTRACT_TRIANGULAR = new xtract_window_types_("XTRACT_TRIANGULAR");
  public final static xtract_window_types_ XTRACT_BARTLETT_HANN = new xtract_window_types_("XTRACT_BARTLETT_HANN");
  public final static xtract_window_types_ XTRACT_BLACKMAN = new xtract_window_types_("XTRACT_BLACKMAN");
  public final static xtract_window_types_ XTRACT_KAISER = new xtract_window_types_("XTRACT_KAISER");
  public final static xtract_window_types_ XTRACT_BLACKMAN_HARRIS = new xtract_window_types_("XTRACT_BLACKMAN_HARRIS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_window_types_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_window_types_.class + " with value " + swigValue);
  }

  private xtract_window_types_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_window_types_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_window_types_(String swigName, xtract_window_types_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_window_types_[] swigValues = { XTRACT_GAUSS, XTRACT_HAMMING, XTRACT_HANN, XTRACT_BARTLETT, XTRACT_TRIANGULAR, XTRACT_BARTLETT_HANN, XTRACT_BLACKMAN, XTRACT_KAISER, XTRACT_BLACKMAN_HARRIS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

