/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface xtractConstants {
  public final static int XTRACT_BARK_BANDS = xtractJNI.XTRACT_BARK_BANDS_get();
  public final static int XTRACT_WINDOW_SIZE = xtractJNI.XTRACT_WINDOW_SIZE_get();
  public final static int XTRACT_NONE = xtractJNI.XTRACT_NONE_get();
  public final static int XTRACT_ANY = xtractJNI.XTRACT_ANY_get();
  public final static int XTRACT_UNKNOWN = xtractJNI.XTRACT_UNKNOWN_get();
  public final static int XTRACT_MAXARGS = xtractJNI.XTRACT_MAXARGS_get();
  public final static int XTRACT_MAX_NAME_LENGTH = xtractJNI.XTRACT_MAX_NAME_LENGTH_get();
  public final static int XTRACT_MAX_AUTHOR_LENGTH = xtractJNI.XTRACT_MAX_AUTHOR_LENGTH_get();
  public final static int XTRACT_MAX_DESC_LENGTH = xtractJNI.XTRACT_MAX_DESC_LENGTH_get();
  public final static int XTRACT_FEATURES = xtractJNI.XTRACT_FEATURES_get();
}
