/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_vector_t {
  public final static xtract_vector_t XTRACT_SPECTRAL = new xtract_vector_t("XTRACT_SPECTRAL");
  public final static xtract_vector_t XTRACT_SPECTRAL_MAGNITUDES = new xtract_vector_t("XTRACT_SPECTRAL_MAGNITUDES");
  public final static xtract_vector_t XTRACT_SPECTRAL_PEAKS = new xtract_vector_t("XTRACT_SPECTRAL_PEAKS");
  public final static xtract_vector_t XTRACT_SPECTRAL_PEAKS_MAGNITUDES = new xtract_vector_t("XTRACT_SPECTRAL_PEAKS_MAGNITUDES");
  public final static xtract_vector_t XTRACT_SPECTRAL_PEAKS_FREQUENCIES = new xtract_vector_t("XTRACT_SPECTRAL_PEAKS_FREQUENCIES");
  public final static xtract_vector_t XTRACT_SPECTRAL_HARMONICS = new xtract_vector_t("XTRACT_SPECTRAL_HARMONICS");
  public final static xtract_vector_t XTRACT_SPECTRAL_HARMONICS_MAGNITUDES = new xtract_vector_t("XTRACT_SPECTRAL_HARMONICS_MAGNITUDES");
  public final static xtract_vector_t XTRACT_SPECTRAL_HARMONICS_FREQUENCIES = new xtract_vector_t("XTRACT_SPECTRAL_HARMONICS_FREQUENCIES");
  public final static xtract_vector_t XTRACT_AUTOCORRELATION_COEFFS = new xtract_vector_t("XTRACT_AUTOCORRELATION_COEFFS");
  public final static xtract_vector_t XTRACT_ARBITRARY_SERIES = new xtract_vector_t("XTRACT_ARBITRARY_SERIES");
  public final static xtract_vector_t XTRACT_AUDIO_SAMPLES = new xtract_vector_t("XTRACT_AUDIO_SAMPLES");
  public final static xtract_vector_t XTRACT_MEL_COEFFS = new xtract_vector_t("XTRACT_MEL_COEFFS");
  public final static xtract_vector_t XTRACT_LPC_COEFFS = new xtract_vector_t("XTRACT_LPC_COEFFS");
  public final static xtract_vector_t XTRACT_LPCC_COEFFS = new xtract_vector_t("XTRACT_LPCC_COEFFS");
  public final static xtract_vector_t XTRACT_BARK_COEFFS = new xtract_vector_t("XTRACT_BARK_COEFFS");
  public final static xtract_vector_t XTRACT_SUBFRAMES = new xtract_vector_t("XTRACT_SUBFRAMES");
  public final static xtract_vector_t XTRACT_NO_DATA = new xtract_vector_t("XTRACT_NO_DATA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_vector_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_vector_t.class + " with value " + swigValue);
  }

  private xtract_vector_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_vector_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_vector_t(String swigName, xtract_vector_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_vector_t[] swigValues = { XTRACT_SPECTRAL, XTRACT_SPECTRAL_MAGNITUDES, XTRACT_SPECTRAL_PEAKS, XTRACT_SPECTRAL_PEAKS_MAGNITUDES, XTRACT_SPECTRAL_PEAKS_FREQUENCIES, XTRACT_SPECTRAL_HARMONICS, XTRACT_SPECTRAL_HARMONICS_MAGNITUDES, XTRACT_SPECTRAL_HARMONICS_FREQUENCIES, XTRACT_AUTOCORRELATION_COEFFS, XTRACT_ARBITRARY_SERIES, XTRACT_AUDIO_SAMPLES, XTRACT_MEL_COEFFS, XTRACT_LPC_COEFFS, XTRACT_LPCC_COEFFS, XTRACT_BARK_COEFFS, XTRACT_SUBFRAMES, XTRACT_NO_DATA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

