/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class xtract_mfcc_types_ {
  public final static xtract_mfcc_types_ XTRACT_EQUAL_GAIN = new xtract_mfcc_types_("XTRACT_EQUAL_GAIN");
  public final static xtract_mfcc_types_ XTRACT_EQUAL_AREA = new xtract_mfcc_types_("XTRACT_EQUAL_AREA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static xtract_mfcc_types_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + xtract_mfcc_types_.class + " with value " + swigValue);
  }

  private xtract_mfcc_types_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private xtract_mfcc_types_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private xtract_mfcc_types_(String swigName, xtract_mfcc_types_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static xtract_mfcc_types_[] swigValues = { XTRACT_EQUAL_GAIN, XTRACT_EQUAL_AREA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

